# Trigger source for the OSS `metrics` example.
#
# Licensed Enterprise `prometheus` and `traces` sources contribute source-bound
# discover/read tools. This sample config only defines a file log source; the
# Compose files in this directory do not mount or start a Versus agent.
#
# To still demonstrate something end-to-end on OSS, we trigger incidents through
# a plain `file` log source: the host-run `scripts/generate_noisy_logs.py`
# appends synthetic app logs to ./logs/app.log (bind-mounted at the path below),
# and a `--spike 5xx` burst emits `level=error ... status=503` lines. Those lines
# start a log incident in a separately configured agent. Licensed metric/trace
# sources can read data pushed by `scripts/generate_fake_metrics.py`.
sources:
  - name: demo-app-logs
    type: file
    enable: true
    file:
      path: /var/log/sample/app.log
      format: text
      from_beginning: true
      max_lines_per_pull: 1000
