import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, Boxes, Cpu, Database, Network, RefreshCw, Search, Server, ShipWheel } from "lucide-react";
import { api, type KubernetesResource } from "@/lib/api";
import { TopBar } from "@/components/TopBar";
import { RetryableError } from "@/components/RetryableError";
import { SkCard } from "@/components/Skeleton";

const stats = [
  ["Nodes", "nodes", Server], ["Pods", "pods", Boxes], ["Workloads", "workloads", ShipWheel],
  ["Namespaces", "namespaces", Network], ["Warnings", "warnings", AlertTriangle],
] as const;

const workloadKinds = new Set(["Deployment", "StatefulSet", "DaemonSet", "Job", "CronJob", "Pod"]);

function asArray<T>(value: T[] | null | undefined): T[] {
  return Array.isArray(value) ? value : [];
}

export function KubernetesPage() {
  const [namespace, setNamespace] = useState("");
  const [committedNamespace, setCommittedNamespace] = useState("");
  const [name, setName] = useState("");
  const [submitted, setSubmitted] = useState("");
  const [selected, setSelected] = useState<KubernetesResource | null>(null);
  const overview = useQuery({ queryKey: ["kubernetes-overview"], queryFn: api.kubernetesOverview, retry: false });
  useEffect(() => {
    const timeout = window.setTimeout(() => setCommittedNamespace(namespace.trim()), 300);
    return () => window.clearTimeout(timeout);
  }, [namespace]);
  const usage = useQuery({ queryKey: ["kubernetes-usage", committedNamespace], queryFn: () => api.kubernetesUsage(committedNamespace), retry: false });
  const workloads = useQuery({ queryKey: ["kubernetes-workloads", committedNamespace], queryFn: () => api.kubernetesWorkloads(committedNamespace), retry: false });
  const topology = useQuery({ queryKey: ["kubernetes-topology", committedNamespace], queryFn: () => api.kubernetesTopology(committedNamespace), retry: false });
  const warnings = useQuery({ queryKey: ["kubernetes-warnings", committedNamespace], queryFn: () => api.kubernetesEvents(committedNamespace), retry: false });
  const search = useQuery({ queryKey: ["kubernetes-search", committedNamespace, submitted], queryFn: () => api.kubernetesSearch(committedNamespace, submitted), enabled: submitted !== "", retry: false });
  const detail = useQuery({ queryKey: ["kubernetes-detail", selected?.resource_id, selected?.namespace, selected?.name], queryFn: () => api.kubernetesDescribe(selected!.resource_id, selected?.namespace ?? "", selected!.name), enabled: selected !== null, retry: false });
  const workloadDetail = useQuery({ queryKey: ["kubernetes-workload", selected?.kind, selected?.namespace, selected?.name], queryFn: () => api.kubernetesWorkload(selected!.kind, selected?.namespace ?? "", selected!.name), enabled: selected !== null && workloadKinds.has(selected.kind), retry: false });
  const topologyNodes = new Map(asArray(topology.data?.nodes).map((node) => [node.id, `${node.kind} ${node.namespace ? `${node.namespace}/` : ""}${node.name}${node.status ? ` (${node.status})` : ""}`]));

  return <main className="min-w-0 flex-1 overflow-auto">
    <TopBar title="Kubernetes" />
    <div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
      <header className="flex flex-col gap-3 border-b border-ink-700 pb-4 sm:flex-row sm:items-end sm:justify-between">
        <div><h1 className="flex items-center gap-2 text-xl font-semibold text-ink-50"><ShipWheel size={20} /> Kubernetes</h1><p className="mt-1 text-sm text-ink-300">{overview.data ? `${overview.data.connector} · ${overview.data.cluster_id}` : "Cluster overview"} · read-only</p></div>
        <label className="text-xs text-ink-300">Namespace<input className="mt-1 block rounded border border-ink-600 bg-ink-900 px-3 py-2 text-ink-50" value={namespace} onChange={(event) => setNamespace(event.target.value)} placeholder="All namespaces" /></label>
      </header>
      {overview.isPending && <div aria-label="Loading Kubernetes overview"><SkCard lines={4} /></div>}
      {overview.isError && <RetryableError error={overview.error} onRetry={() => overview.refetch()} retrying={overview.isRefetching} context="Couldn't load Kubernetes overview" />}
      {overview.data && <>
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{stats.map(([label, key, Icon]) => <div className="border-b border-ink-700 p-3" key={key}><Icon size={16} className="text-accent-300" aria-hidden="true" /><div className="mt-2 text-2xl font-semibold text-ink-50">{overview.data[key]}</div><div className="text-xs text-ink-400">{label}</div></div>)}</div>
        <div className="flex flex-wrap items-center gap-3 text-xs text-ink-400"><span>Nodes ready {overview.data.ready_nodes}/{overview.data.nodes}</span><span>Pods running {overview.data.running_pods}/{overview.data.pods}</span><span>Namespaces active {overview.data.active_namespaces}/{overview.data.namespaces}</span><span>Observed {new Date(overview.data.observed_at).toLocaleString()}</span><button className="btn ml-auto" onClick={() => { overview.refetch(); usage.refetch(); workloads.refetch(); topology.refetch(); warnings.refetch(); }}><RefreshCw size={13} /> Refresh</button></div>
        <div className="grid gap-3 border-y border-ink-700 py-3 text-xs sm:grid-cols-2">
          <div><Cpu size={14} className="mb-1 text-accent-300" /><span className="text-ink-400">CPU requested / limited / allocatable / usage</span><p className="mt-1 break-words text-ink-100">{overview.data.requested_cpu ?? "Unavailable"} / {overview.data.limited_cpu ?? "Unavailable"} / {overview.data.allocatable_cpu ?? "Unavailable"} / {overview.data.usage_cpu ?? "Unavailable"}</p></div>
          <div><Database size={14} className="mb-1 text-accent-300" /><span className="text-ink-400">Memory requested / limited / allocatable / usage</span><p className="mt-1 break-words text-ink-100">{overview.data.requested_memory ?? "Unavailable"} / {overview.data.limited_memory ?? "Unavailable"} / {overview.data.allocatable_memory ?? "Unavailable"} / {overview.data.usage_memory ?? "Unavailable"}</p></div>
        </div>
        <p role="status" className="text-xs text-ink-300">Metrics {overview.data.metrics_status ?? "unavailable"} · source {(overview.data.usage_source ?? "unavailable").replace("_", " ")}{overview.data.metrics_observed_at ? ` · sampled ${new Date(overview.data.metrics_observed_at).toLocaleString()}` : " · no samples"}{overview.data.metrics_status !== "unavailable" && !overview.data.metrics_fresh ? " · stale" : ""}</p>
        <p role="status" className="text-xs text-ink-300">{usage.isPending ? "Loading usage samples" : usage.isError ? "Usage samples unavailable" : (usage.data?.availability ?? "unavailable") === "unavailable" ? "Usage unavailable" : `Usage ${usage.data?.fresh ? "fresh" : "stale"} · ${asArray(usage.data?.pods).length} pod samples · ${asArray(usage.data?.nodes).length} node samples${usage.data?.truncated ? " · partial" : ""}`}</p>
        {(overview.data.partial_failures?.length ?? 0) > 0 && <div role="status" className="border-l-2 border-sev-warning px-3 py-2 text-xs text-ink-200">Partial cluster visibility: {overview.data.partial_failures?.map((failure) => failure.class).join(", ")}</div>}
        {overview.data.truncated && <div role="status" className="border-l-2 border-sev-warning px-3 py-2 text-xs text-ink-200">Overview reached its collection bound. Some categories are omitted.</div>}
      </>}
      <section aria-labelledby="kubernetes-workloads"><h2 id="kubernetes-workloads" className="text-sm font-semibold text-ink-100">Workloads</h2>{workloads.isError && <p role="status" className="mt-2 text-sm text-sev-warning">Workload inventory is unavailable.</p>}{workloads.data && <><div className="mt-2 divide-y divide-ink-700 border-y border-ink-700">{asArray(workloads.data.items).map((item) => <button type="button" onClick={() => setSelected(item)} key={`${item.resource_id}:${item.namespace}:${item.name}`} className="flex w-full items-center justify-between gap-3 py-2 text-left text-sm"><span className="min-w-0 truncate text-ink-50">{item.name}</span><span className="shrink-0 text-xs text-ink-400">{item.kind} {item.namespace}</span></button>)}</div>{asArray(workloads.data.items).length === 0 && <p className="mt-2 text-sm text-ink-400">No workloads in this scope.</p>}{(workloads.data.truncated || workloads.data.partial_failures?.length) ? <p role="status" className="mt-2 text-xs text-sev-warning">Workload inventory is partial{workloads.data.partial_failures?.some((failure) => failure.class === "forbidden") ? " because some kinds are forbidden" : ""}.</p> : null}</>}</section>
      <form className="flex flex-col gap-2 border-y border-ink-700 py-4 sm:flex-row" onSubmit={(event) => { event.preventDefault(); setSubmitted(name.trim()); }}>
        <input aria-label="Resource name" className="min-w-0 flex-1 rounded border border-ink-600 bg-ink-900 px-3 py-2 text-sm text-ink-50" value={name} onChange={(event) => setName(event.target.value)} placeholder="Search names across resource kinds" />
        <button className="btn" type="submit"><Search size={14} /> Search</button>
      </form>
      {search.data && <section aria-labelledby="kubernetes-search-results"><h2 id="kubernetes-search-results" className="text-sm font-semibold text-ink-100">Search results</h2><div className="mt-2 divide-y divide-ink-700 border-y border-ink-700">{asArray(search.data.items).map((item) => <button type="button" onClick={() => setSelected(item)} key={`${item.resource_id}:${item.namespace}:${item.name}`} className="flex w-full justify-between gap-3 py-2 text-left text-sm"><span className="min-w-0 truncate text-ink-50">{item.name}</span><span className="shrink-0 text-xs text-ink-400">{item.kind} {item.namespace}</span></button>)}</div>{asArray(search.data.items).length === 0 && <p className="mt-2 text-sm text-ink-400">No matching resources.</p>}{(search.data.truncated || search.data.partial_failures?.length) ? <p role="status" className="mt-2 text-xs text-sev-warning">Search is partial{search.data.partial_failures?.some((failure) => failure.class === "forbidden") ? " because some resource kinds are forbidden" : ""}.</p> : null}</section>}
      {selected && <section aria-labelledby="kubernetes-resource-detail"><h2 id="kubernetes-resource-detail" className="text-sm font-semibold text-ink-100">Resource detail</h2>{detail.isPending && <SkCard lines={4} />}{detail.isError && <p role="status" className="mt-2 text-sm text-sev-warning">Resource detail is unavailable.</p>}{detail.data && <div className="mt-2 border-y border-ink-700 py-3 text-sm"><p className="font-medium text-ink-50">{detail.data.resource.kind} {detail.data.resource.namespace ? `${detail.data.resource.namespace}/` : ""}{detail.data.resource.name}</p><dl className="mt-3 grid gap-2 text-xs sm:grid-cols-2">{Object.entries(detail.data.resource.summary ?? {}).filter(([, value]) => typeof value !== "object").map(([key, value]) => <div key={key}><dt className="text-ink-400">{key.replaceAll("_", " ")}</dt><dd className="break-words text-ink-100">{String(value)}</dd></div>)}</dl>{detail.data.resource.conditions?.map((condition) => <p className="mt-2 text-xs text-ink-300" key={condition.type}>{condition.type}: {condition.status} {condition.reason}</p>)}{detail.data.related_resources?.length ? <p className="mt-2 text-xs text-ink-300">Related: {detail.data.related_resources.map((item) => `${item.kind} ${item.name}`).join(", ")}</p> : null}{detail.data.events?.length ? <p className="mt-2 text-xs text-ink-300">Diagnostic events: {detail.data.events.length}</p> : null}{detail.data.resource.projection_truncated?.length ? <p role="status" className="mt-2 text-xs text-sev-warning">Projection truncated: {detail.data.resource.projection_truncated.join(", ")}</p> : null}</div>}{workloadDetail.data && <div className="border-b border-ink-700 py-3 text-xs text-ink-200"><p>Desired {workloadDetail.data.desired ?? "n/a"} · ready {workloadDetail.data.ready ?? "n/a"} · available {workloadDetail.data.available ?? "n/a"} · unavailable {workloadDetail.data.unavailable ?? "n/a"}</p><p className="mt-1">Strategy {workloadDetail.data.update_strategy ?? "n/a"} · generation {workloadDetail.data.observed_generation ?? "n/a"}/{workloadDetail.data.generation ?? "n/a"}</p>{workloadDetail.data.pods?.map((pod) => <p className="mt-1" key={pod.name}>{pod.name}: {pod.phase ?? "unknown"}, node {pod.node ?? "unassigned"}, restarts {pod.restart_count}</p>)}</div>}</section>}
      <section aria-labelledby="kubernetes-warnings"><h2 id="kubernetes-warnings" className="text-sm font-semibold text-ink-100">Recent warnings</h2>{warnings.data && <><div className="mt-2 divide-y divide-ink-700 border-y border-ink-700">{asArray(warnings.data.items).map((event) => <div className="py-2 text-xs" key={`${event.namespace}:${event.name}`}><p className="text-ink-100">{String(event.summary?.reason ?? event.name)}</p><p className="mt-1 break-words text-ink-400">{String(event.summary?.message ?? "Warning event")}</p></div>)}{asArray(warnings.data.items).length === 0 && <p className="py-3 text-sm text-ink-400">No recent warning events.</p>}</div>{(warnings.data.truncated || warnings.data.partial_failures?.length) ? <p role="status" className="mt-2 text-xs text-sev-warning">Warning evidence is partial.</p> : null}</>}</section>
      <section aria-labelledby="kubernetes-topology"><h2 id="kubernetes-topology" className="text-sm font-semibold text-ink-100">Topology</h2>{topology.isPending && <SkCard lines={3} />}{topology.isError && <p role="status" className="mt-2 text-sm text-sev-warning">Topology is unavailable.</p>}{topology.data && <><div className="mt-2 overflow-x-auto border-y border-ink-700" tabIndex={0} aria-label="Kubernetes topology graph"><div role="list" className="grid min-w-0 grid-cols-2 gap-x-2 text-xs sm:min-w-[36rem] sm:gap-x-6">{asArray(topology.data.edges).map((edge, index) => { const from = topologyNodes.get(edge.from) ?? edge.from; const to = topologyNodes.get(edge.to) ?? edge.to; const evidence = edge.intent ? "intent" : "observed"; return <div role="listitem" tabIndex={0} aria-label={`${from} ${edge.type} ${to}, ${evidence}`} key={`${edge.from}:${edge.to}:${index}`} className="col-span-2 grid min-w-0 grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] items-center gap-2 border-b border-ink-800 py-2 sm:gap-3"><span className="truncate text-right text-ink-200">{from}</span><span className="text-center text-ink-500">{edge.type}<span className="block text-2xs">{evidence}</span></span><span className="truncate text-ink-200">{to}</span></div>; })}</div>{asArray(topology.data.edges).length === 0 && <p className="p-4 text-sm text-ink-400">No topology edges in this scope.</p>}</div>{(topology.data.truncated || topology.data.partial_failures?.length) && <p role="status" className="mt-2 text-xs text-sev-warning">Topology is partial{topology.data.truncated ? " and reached its node or edge bound" : ""}{topology.data.partial_failures?.some((failure) => failure.class === "forbidden") ? "; some categories are forbidden" : ""}.</p>}</>}</section>
    </div>
  </main>;
}